# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1ab647eaefe6433c3304baa386ea1b364b5575e45eb2128e35097e96ea94af7333ff0a6683b765b2df2fb6a17e128812d593adeb889decd09195abed9352ea7

test:
  secret_key_base: 5af494218c55e40a7f2427646b039f760d06ad9c9f9e54494d09826f3ab93b738f1b0b2440f488674c794c166a0216162da93fc47a618d9ff1d153d4098d8861

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
